# Generated by Django 5.0.6 on 2024-06-30 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Nuevo Proyecto', max_length=200)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('project_budget', models.IntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='user.userprofile')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('valor', models.FloatField(default=0.0)),
                ('presupuesto', models.FloatField(default=0.0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='proyecto.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigo', models.CharField(max_length=15)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tema', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='proyecto.proyecto')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
